// Default content seeded from Charlotte's document. Used as the editor's
// initial values AND as the rendered fallback until she saves edits.

export const HOME_INTRO =
  'Shuyao “Charlotte” Wang is a conductor, composer, vocalist, and instrumentalist whose work bridges choral, orchestral, and literary imagination. Charlotte seeks to tell stories that feel both deeply personal and universally resonant — through music and words.';

export const ABOUT_BIO = [
  'Shuyao “Charlotte” Wang (b. 2000) is a conductor whose work spans orchestral and choral repertoire, shaped by a strong background in both instrumental and vocal music. She approaches conducting as a practice of listening, clarity, and collaboration, drawing on her experience as a composer, soprano, collaborative pianist, as well as her orchestral experience as a percussionist and violist.',
  'In Fall 2025, Charlotte began a Master of Music in Choral Conducting at the University of Michigan, studying conducting with the acclaimed Dr. Eugene Rogers. She co-conducted the SMTD Orpheus Singers and assisted Voices Valiant, a local senior choir. Off the podium, she continued her passion for musical collaboration while furthering her study in voice with distinguished tenor Stanford Olsen and collaborative piano with Dr. Ana María Otamendi, a leading figure in the field. Besides professional and conservatory gigs, Charlotte also collaborates with musicians at different levels; these experiences continue to shape her understanding of the conductor as both a musical leader and a human connector within an ensemble.',
  'Charlotte graduated summa cum laude from Amherst College with a Bachelor of Arts in Music, Mathematics, and English. During her time at Amherst, she served as Assistant Conductor of the Amherst Symphony Orchestra and Amherst Choral Society, studying orchestral conducting with Mark Swanson, choral conducting with Arianne Abela, and composition with Eric Sawyer. Her honors thesis in music culminated in the composition and performance of her choral-orchestral work, Requiem: Ceaseless Life. Upon graduation, she was awarded The Eric Edward Sundquist Prize in Music. Following graduation, she remained at Amherst as a Graduate Associate of Music, continuing to assist in rehearsals and performances, conduct sectionals and smaller ensembles, and support music theory instruction. After she left Amherst, she was later awarded the Edward Poole Lay ’22 Fellowship for two consecutive years in support of her graduate study in music.',
  'Her conducting training includes participation in professional institutes, festivals, and masterclasses, where she has worked with conductors such as Neil Varon, Miguel Harth-Bedoya, Donald Schleicher, Farkhad Khudyev, Jonathan Girard, David Jacobs, Jerry Blackstone, William Weinert, Jeffery Douma, Deanna Joseph, and Daniel Bara. She has conducted and assisted in a wide range of symphonic and choral repertoire and continues to develop a clear, efficient physical technique and a thoughtful rehearsal process, in addition to her passion for and understanding of music.',
].join('\n\n');

export const ABOUT_STATEMENT =
  'At this early stage of her career, Charlotte is still discovering what kind of conductor, musician, and person she hopes to become. What she knows clearly is her love for music as a shared human experience, and her desire to create rehearsal rooms where people feel heard, trusted, and inspired to give their best. In addition to professionalism and perfectionism, she approaches conducting with curiosity and care, believing that clarity, generosity, and interpersonal connection are what allow music to truly come alive.';

export const WRITING_INTRO = [
  'Charlotte has been a writer first, perhaps long before she became a musician. Addicted to reading and writing from an early age, she excelled throughout her schooling in Chinese language and literature (the equivalent of English class in English-speaking countries) and received various writing prizes, including awards at the national level. For a long time, she believed she would become a writer or scholar in literature.',
  'Charlotte was admitted to Amherst College as a prospective English major, where she explored literature in many forms through the rich resources of Amherst’s distinguished English department. She dived into both critical and creative writing, while also taking cross-listed courses in education studies, American studies, legal studies, and theatre. Fluent in French, she also spent a year studying French literature in the original language. Across these studies, she became especially drawn to twentieth-century literature, with particular interests in time, memory, trauma, and the shaping of human consciousness — perhaps connected to her musician’s natural fascination with time.',
  'Charlotte writes extensively in both English and Chinese, with occasional work and adaptation in French. Her writing spans many creative genres, including fiction, nonfiction, poetry, and drama, as well as academic essays, publication contributions, and critical literary analysis. Though she later turned her primary professional commitment toward music, she continued her deep involvement in literature. At Amherst, she completed the English major with dedication and passion and wrote an honors thesis that received the only summa recommendation among creative English theses in her year.',
  'Although Charlotte is not currently pursuing a career in literature or publication, she considers writing an essential part of her identity. She may one day return to a larger literary project, but for now, writing remains woven into her daily life: a way of thinking, remembering, imagining, and understanding the world. She writes every day, and she will never stop writing.',
].join('\n\n');
